name: Weekly FotMob Scraper

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  scrape_fotmob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t fotmob-scraper .

      - name: Run FotMob Scraper
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          docker run --rm \
            -e DB_URL \
            fotmob-scraper